/**
 * One-shot script to rename existing bots with realistic usernames.
 *
 * Replaces the old `{abbr}_{personalityType}_{suffix}` pattern with
 * natural-looking usernames generated by the username-generator module.
 *
 * Run: npx tsx apps/web/scripts/rename-bots.ts
 */

import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';
import { resolve } from 'path';
import {
  generateBotUsername,
  generateBotDisplayName,
  type SchoolInfo,
} from '../lib/admin/bots/username-generator';

// Load .env.local if env vars are not set
if (!process.env.SUPABASE_SERVICE_ROLE_KEY) {
  const candidates = [
    resolve(process.cwd(), '.env.local'),
    resolve(process.cwd(), 'apps', 'web', '.env.local'),
  ];
  for (const envPath of candidates) {
    try {
      const envContent = readFileSync(envPath, 'utf8');
      for (const line of envContent.split('\n')) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const eqIdx = trimmed.indexOf('=');
        if (eqIdx < 1) continue;
        const key = trimmed.slice(0, eqIdx);
        const val = trimmed.slice(eqIdx + 1).replace(/^"|"$/g, '');
        if (!process.env[key]) process.env[key] = val;
      }
      break;
    } catch { /* try next */ }
  }
}

const supabaseUrl =
  process.env.NEXT_PUBLIC_SUPABASE_URL ||
  'https://lazwferoamyntvrgsqcu.supabase.co';
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || '';

if (!supabaseKey) {
  console.error(
    'SUPABASE_SERVICE_ROLE_KEY is required. Set it in your .env.local'
  );
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

/**
 * Detect whether a username still matches the old bot naming convention:
 *   {abbr}_{personalityType}_{digit}
 * e.g. "ala_homer_1", "usc_analyst_1", "lsu_hot_take_1"
 */
const OLD_BOT_PATTERN = /^[a-z]+_(homer|analyst|hot_take|old_school|recruiting_insider|recruiting)_\d+$/;

function needsRename(username: string): boolean {
  return OLD_BOT_PATTERN.test(username);
}

async function renameBots() {
  console.log('=== Renaming CFB Social Bots ===\n');

  // Fetch all bots with their school info
  const { data: bots, error: fetchError } = await supabase
    .from('profiles')
    .select(
      'id, username, display_name, bot_personality, school_id, school:schools!profiles_school_id_fkey(name, mascot, abbreviation)'
    )
    .eq('is_bot', true)
    .order('created_at');

  if (fetchError) {
    console.error('Failed to fetch bots:', fetchError.message);
    process.exit(1);
  }

  if (!bots?.length) {
    console.log('No bots found.');
    return;
  }

  console.log(`Found ${bots.length} bots total.\n`);

  let renamed = 0;
  let skipped = 0;
  const errors: string[] = [];

  for (const bot of bots) {
    const oldUsername = bot.username || '';

    // Skip bots that already have realistic usernames
    if (!needsRename(oldUsername)) {
      skipped++;
      continue;
    }

    // Extract personality type from bot_personality object
    const personality = bot.bot_personality as Record<string, unknown> | null;
    const personalityType =
      (personality?.name as string) ||
      (personality?.type as string) ||
      'homer';

    // Build SchoolInfo from joined school data
    const schoolData = Array.isArray(bot.school) ? bot.school[0] : bot.school;
    const school: SchoolInfo | null = schoolData
      ? {
          name: (schoolData as Record<string, unknown>).name as string,
          mascot: (schoolData as Record<string, unknown>).mascot as string,
          abbreviation: (schoolData as Record<string, unknown>)
            .abbreviation as string,
        }
      : null;

    // Generate new username and display name
    const newUsername = generateBotUsername(school, personalityType);
    const newDisplayName = generateBotDisplayName(school, personalityType);

    try {
      // Update the profile
      const { error: updateError } = await supabase
        .from('profiles')
        .update({
          username: newUsername,
          display_name: newDisplayName,
        })
        .eq('id', bot.id);

      if (updateError) {
        errors.push(`${oldUsername}: profile update failed - ${updateError.message}`);
        continue;
      }

      // Update auth user metadata so username stays in sync
      const { error: authError } = await supabase.auth.admin.updateUserById(
        bot.id,
        {
          user_metadata: {
            username: newUsername,
            display_name: newDisplayName,
          },
        }
      );

      if (authError) {
        errors.push(`${oldUsername}: auth metadata update failed - ${authError.message}`);
        // Profile was already updated, so still count it but log the warning
      }

      renamed++;
      console.log(
        `[${renamed}] ${oldUsername} -> ${newUsername} (${newDisplayName})`
      );
    } catch (err) {
      errors.push(
        `${oldUsername}: ${err instanceof Error ? err.message : String(err)}`
      );
    }
  }

  // Summary
  console.log('\n=== Rename Complete ===');
  console.log(`Renamed: ${renamed}`);
  console.log(`Skipped (already realistic): ${skipped}`);
  console.log(`Total: ${bots.length}`);

  if (errors.length > 0) {
    console.log(`\nErrors (${errors.length}):`);
    for (const err of errors) {
      console.log(`  - ${err}`);
    }
  }
}

renameBots().catch(console.error);
