// ============================================================
// CFB Social - All Application Enums
// ============================================================

export enum UserRole {
  USER = 'USER',
  PREMIUM = 'PREMIUM',
  MODERATOR = 'MODERATOR',
  EDITOR = 'EDITOR',
  ADMIN = 'ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  BANNED = 'BANNED',
}

export enum PostType {
  STANDARD = 'STANDARD',
  RECEIPT = 'RECEIPT',
  SIDELINE = 'SIDELINE',
  PREDICTION = 'PREDICTION',
  AGING_TAKE = 'AGING_TAKE',
  CHALLENGE_RESULT = 'CHALLENGE_RESULT',
}

export enum PostStatus {
  PUBLISHED = 'PUBLISHED',
  FLAGGED = 'FLAGGED',
  REMOVED = 'REMOVED',
  DRAFT = 'DRAFT',
}

export enum ReactionType {
  TOUCHDOWN = 'TOUCHDOWN',
  FUMBLE = 'FUMBLE',
}

export enum DynastyTier {
  WALK_ON = 'WALK_ON',
  STARTER = 'STARTER',
  ALL_CONFERENCE = 'ALL_CONFERENCE',
  ALL_AMERICAN = 'ALL_AMERICAN',
  HEISMAN = 'HEISMAN',
  HALL_OF_FAME = 'HALL_OF_FAME',
}

export enum ChallengeStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  VOTING = 'VOTING',
  COMPLETED = 'COMPLETED',
  DECLINED = 'DECLINED',
  EXPIRED = 'EXPIRED',
}

export enum PortalPlayerStatus {
  IN_PORTAL = 'IN_PORTAL',
  COMMITTED = 'COMMITTED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum PredictionResult {
  PENDING = 'PENDING',
  CORRECT = 'CORRECT',
  INCORRECT = 'INCORRECT',
  PUSH = 'PUSH',
  EXPIRED = 'EXPIRED',
}

export enum ModerationAction {
  FLAG = 'FLAG',
  REMOVE = 'REMOVE',
  RESTORE = 'RESTORE',
  WARN = 'WARN',
  SUSPEND = 'SUSPEND',
  BAN = 'BAN',
  DISMISS = 'DISMISS',
}

export enum ReportReason {
  SPAM = 'SPAM',
  HARASSMENT = 'HARASSMENT',
  HATE_SPEECH = 'HATE_SPEECH',
  OFF_TOPIC = 'OFF_TOPIC',
  POLITICS = 'POLITICS',
  MISINFORMATION = 'MISINFORMATION',
  OTHER = 'OTHER',
}

export enum ReportStatus {
  PENDING = 'PENDING',
  REVIEWING = 'REVIEWING',
  ACTIONED = 'ACTIONED',
  DISMISSED = 'DISMISSED',
}

export enum AppealStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  DENIED = 'DENIED',
}

export enum NotificationType {
  FOLLOW = 'FOLLOW',
  TOUCHDOWN = 'TOUCHDOWN',
  FUMBLE = 'FUMBLE',
  REPLY = 'REPLY',
  REPOST = 'REPOST',
  MENTION = 'MENTION',
  CHALLENGE_RECEIVED = 'CHALLENGE_RECEIVED',
  CHALLENGE_RESULT = 'CHALLENGE_RESULT',
  PREDICTION_RESULT = 'PREDICTION_RESULT',
  RIVALRY_FEATURED = 'RIVALRY_FEATURED',
  PORTAL_COMMIT = 'PORTAL_COMMIT',
  ACHIEVEMENT_UNLOCKED = 'ACHIEVEMENT_UNLOCKED',
  MODERATION_WARNING = 'MODERATION_WARNING',
  MODERATION_APPEAL_RESULT = 'MODERATION_APPEAL_RESULT',
  LEVEL_UP = 'LEVEL_UP',
  AGING_TAKE_SURFACED = 'AGING_TAKE_SURFACED',
  RECEIPT_VERIFIED = 'RECEIPT_VERIFIED',
  SYSTEM = 'SYSTEM',
}

export enum AchievementCategory {
  SOCIAL = 'SOCIAL',
  PREDICTION = 'PREDICTION',
  RIVALRY = 'RIVALRY',
  RECRUITING = 'RECRUITING',
  ENGAGEMENT = 'ENGAGEMENT',
  MILESTONE = 'MILESTONE',
}

export enum XPSource {
  POST_CREATED = 'POST_CREATED',
  TOUCHDOWN_RECEIVED = 'TOUCHDOWN_RECEIVED',
  CHALLENGE_WON = 'CHALLENGE_WON',
  PREDICTION_CORRECT = 'PREDICTION_CORRECT',
  PORTAL_CLAIM_CORRECT = 'PORTAL_CLAIM_CORRECT',
  RIVALRY_PARTICIPATION = 'RIVALRY_PARTICIPATION',
  FACT_CHECK = 'FACT_CHECK',
  ACHIEVEMENT_UNLOCKED = 'ACHIEVEMENT_UNLOCKED',
  DAILY_LOGIN = 'DAILY_LOGIN',
  STREAK_BONUS = 'STREAK_BONUS',
  RECEIPT_VERIFIED = 'RECEIPT_VERIFIED',
  AGING_TAKE_CORRECT = 'AGING_TAKE_CORRECT',
}

export enum LeaderboardPeriod {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  SEASON = 'SEASON',
  ALL_TIME = 'ALL_TIME',
}

export enum SchoolClassification {
  FBS = 'FBS',
  FCS = 'FCS',
  D2 = 'D2',
  D3 = 'D3',
  NAIA = 'NAIA',
}
